### ISSUE TITLE
resetPoint clean reputations?

### ISSUE THREAD

**Issue by snipiba** [qcod/laravel-gamify#20]
Maybe i don't get it, but, when is called resetPoint(), then... probably it means, that all badges and reputations may be removed too, or not?

**Comment by saqueib** [comment]
Yes it will remove all the reputation because whenever point changes it syncs all the badges. check this https://github.com/qcod/laravel-gamify/blob/master/src/HasBadges.php#L31 where it does Eloquent relation sync.

If you don't want this I can make it configurable using `syncWithoutDetaching` so that it will keep all old reputation but it won't be consistent with points anymore.
